apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  selector:
    app: pythonapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer
  selector:
    app: pythonapp