apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: saikiranmerugu74/pythonapp:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: "10m"
            memory: "20Mi"
          limits:
            cpu: "20m"
            memory: "40Mi"
