apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: saikiranmerugu74/pythonapp:latest
        ports:
        - containerPort: 80
